<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ArchitectureAI.Application\ArchitectureAI.Application.csproj" />
    <ProjectReference Include="..\ArchitectureAI.Infrastructure\ArchitectureAI.Infrastructure.csproj" />
    <ProjectReference Include="..\ArchitectureAI.Persistence\ArchitectureAI.Persistence.csproj" />
  </ItemGroup>
</Project>
